version: '2'
services:
  terraform:
    #image: ubuntu:latest
    build: .
    container_name: terraform
    volumes:
      - ./src:/go/src
    env_file:
      - credentials.env
    command: /bin/bash
    stdin_open: true
    tty: true
    working_dir: /go/src
